---
- name: Instalar driver php-mysql
  hosts: all
  tasks:
    - name: Install PHP-MySQL
      apt:
        name: 'php-mysql'

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
